#!/usr/bin/env ansible-playbook
---

# https://www.tutorialspoint.com/articles/find-my-public-ip-address-from-linux-command-line

- hosts: all
  gather_facts: False

  tasks:
    - git_config:
        name: user.email
        scope: local
        repo: '{{ playbook_dir }}'
      register: git_config
      delegate_to: localhost
    - cron:
        cron_file: &name mail-my-ip
        name: *name
        user: root
        minute: 5
        job: >-
          dig +short myip.opendns.com @resolver1.opendns.com
          | mail -s '{{ ansible_hostname }} IP' {{ git_config.config_value }}
      become: True
